
modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]] #mandatory
modId = "ex_enigmaticlegacy" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
[[dependencies."ex_enigmaticlegacy"]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"# Here's another dependency
[[dependencies."ex_enigmaticlegacy"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
curios ="forge-5.14.1+1.20.1"
